[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "solmate/=lib/solmate/src/",
  "erc721a/=lib/ERC721A/contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
